services:
  php-apache-environment:
    image: template8:1.0.0
    container_name: template8
    build:
      context: ./
      dockerfile: docker/Dockerfile
    volumes:
      - ./html:/var/www/html/
      - ./secure:/var/www/secure/
    ports:
      - '${APP_PORT}:80'
